openapi: "3.0.0"

info:
  title: "FAVORITE ATLASSIAN DataCenter REST API"
  version: "1.0.0"

servers:
  - url: http://0.0.0.0

tags:
  - name: "Jira"
  - name: "JSM"
  - name: "Insight/Asset"
  - name: "Confluence"
  - name: "Bitbucket"
  - name: "Bamboo"

paths:

  /rest/servicedeskapi/organization:
    get:
      tags:
        - "JSM"
      summary: Get JSM Organization
      responses:
        200:
          description: Succeed
  
  /rest/insight/1.0/object/{objectId}/attributes:
    get:
      tags:
        - "Insight/Asset"
      description: Get Insight object attributes
      responses:
        200:
          description: Succeed

