openapi: "3.0.0"

info:
  title: "FAVORITE ATLASSIAN DataCenter REST API"
  version: "1.0.0"

servers:
  - url: http://0.0.0.0

tags:
  - name: "Jira"
  - name: "JSM"
  - name: "Insight/Asset"
  - name: "Confluence"
  - name: "Bitbucket"
  - name: "Bamboo"

paths:

  /rest/servicedeskapi/organization:
    get:
      tags:
        - "JSM"
      summary: Get JSM Organization
      responses:
        200:
          description: Succeed
  
  /rest/insight/1.0/object/{objectId}/attributes:
    get:
      tags:
        - "Insight/Asset"
      description: Get Insight object attributes
      responses:
        200:
          description: Succeed

  /rest/api/latest/plan.json:
    get:
      tags:
        - "Bamboo"
      description: List Bamboo plans 
      responses:
        200:
          description: Succeed

  /rest/api/latest/result/{planKey}:
    get:
      tags:
        - "Bamboo"
      description: List Bamboo plan results
      parameters:
        - name: planKey
          description: Plan key
          in: path
          required: true
          schema:
            type: string
            example: PLAN-P
        - name: max-results
          description: Set results max items
          in: query
          required: false
          schema:
            type: string
            example: 10
      responses:
        200:
          description: Succeed

  /rest/api/latest/result/{buildKey}:
    get:
      tags:
        - "Bamboo"
      description: List Bamboo build results
      parameters:
        - name: buildKey
          description: Build key
          in: path
          required: true
          schema:
            type: string
            example: Build
      responses:
        200:
          description: Succeed

  /rest/api/latest/deploy/project/all:
    get:
      tags:
        - "Bamboo"
      description: List Bamboo deployment projects
      responses:
        200:
          description: Succeed
